name: "Notify users based on issue labels"

on:
  issues:
      types: [labeled]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
        - uses: jenschelkopf/issue-label-notification-action@f7d2363e5efa18b8aeea671ca8093e183ae8f218 # 1.3
          with:
             recipients: |
                  team/extensibility=@joelkw @muratsu @tjkandala
                  team/frontend-platform=@alicjasuska @felixfbecker @umpox @valerybugakov @5h1ru @pdubroy
                  team/core-application=@tsenart
                  team/search=@lguychard @limitedmage
                  team/code-intelligence=@macraig
                  team/code-insights=@joelkw @felixfbecker @vovakulikov
                  team/distribution=@pecigonzalo
